name: Build and Release

on:
  workflow_dispatch: # This allows you to manually trigger the workflow from the GitHub Actions tab

jobs:
  release:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
      
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Install Dependencies
        run: npm install
        
      - name: Build and Publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          if [ "${{ runner.os }}" == "Windows" ]; then
            npm run publish:win
          else
            npm run publish:mac
          fi
